defaults:
  - _self_
  - task@_global_: quadruped_walk
  - agent@_global_: taco
  - override hydra/launcher: submitit_local

domain: dmc
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: false
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
encoder_lr: 1e-4
feature_dim: 50
exp_name: default


hydra:
  run:
    dir: ./exp_local/${exp_name}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm